services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: {{ cookiecutter.project_slug.replace('-', '_').replace(' ', '_') }}_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .

    volumes: []
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A {{ cookiecutter.project_slug }} worker --loglevel=info
    volumes: []
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A {{ cookiecutter.project_slug }} beat --loglevel=info
    volumes: []
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: